### PR TITLE
fix apiSecret not working bug

### PR DESCRIPTION
**Pull request by baihua666**
fix apiSecret not working bug,test with video call plugin

### CODE REVIEW

**Review by shivanshtalwar0 — CHANGES_REQUESTED** [review]
You can add same onError for other plugin examples aswell i think that should be a standard feature

**Comment by baihua666** [comment]
https://github.com/flutterjanus/flutter_janus_client/pull/62/commits/8ce8f48c874cd8cc135ed455b0f0bce652a73449
add error hanld for audio bridge,streaming,video room plugin,video room plugin tested,I don't know how to test others.

**Comment by shivanshtalwar0** [comment]
Thanks dude! Will do a sanity testing and if everything goes well will merge

**Comment by shivanshtalwar0** [comment]
@all-contributors please add @baihua666  for bugfixes and improvements

**Comment by shivanshtalwar0** [comment]
@all-contributors please add @baihua666 for bug

**Pull request merged**
